export const BNSENTMIX_SAMPLES = [
  { id: "bn001", text: "Daraz er sale ta onek bhalo, kintu delivery late hoy", sentiment: "mixed" },
  { id: "bn002", text: "bKash diye payment kora shobcheye easy", sentiment: "positive" },
  { id: "bn003", text: "Pathao driver rude chilo, never again", sentiment: "negative" },
  { id: "bn004", text: "Ei ad ta cringe lage, meme banano uchit", sentiment: "negative" },
  { id: "bn005", text: "Bangla slogan ta actually relatable", sentiment: "positive" },
  { id: "bn006", text: "Price barano mane customer ke fool kora", sentiment: "negative" },
  { id: "bn007", text: "Sylhet e ei campaign ta bujhte parbo na", sentiment: "negative" },
  { id: "bn008", text: "Metro-centric ad, grame mane hobe na", sentiment: "negative" },
  { id: "bn009", text: "Influencer fake follower use korse clearly", sentiment: "negative" },
  { id: "bn010", text: "Cashback offer ta genuinely helpful", sentiment: "positive" },
  { id: "bn011", text: "Brand ta trust kora jay na, scam vibe", sentiment: "negative" },
  { id: "bn012", text: "Eid campaign ta emotional touch dilo", sentiment: "positive" },
  { id: "bn013", text: "Advance payment nile product ashe na", sentiment: "negative" },
  { id: "bn014", text: "COD option thakle valo hoto", sentiment: "neutral" },
  { id: "bn015", text: "Essential jinish er daam barano illegal", sentiment: "negative" },
  { id: "bn016", text: "Religious sentiment niye ad korar dorkar nai", sentiment: "negative" },
  { id: "bn017", text: "Women empowerment angle ta forced mone hoy", sentiment: "negative" },
  { id: "bn018", text: "Viral hobe ei slogan ta for wrong reasons", sentiment: "negative" },
  { id: "bn019", text: "Competitor er cheye better messaging", sentiment: "positive" },
  { id: "bn020", text: "Journalist ra eita niye headline banabe", sentiment: "negative" },
  { id: "bn021", text: "TikTok e roast hoye jabe 100%", sentiment: "negative" },
  { id: "bn022", text: "Local language use korar jonno respect", sentiment: "positive" },
  { id: "bn023", text: "Fake discount, original price barano", sentiment: "negative" },
  { id: "bn024", text: "Customer service zero, ad budget high", sentiment: "negative" },
  { id: "bn025", text: "Chittagong dialect missing, feels Dhaka-only", sentiment: "negative" },
  { id: "bn026", text: "Meme template ready, screenshot kore felbo", sentiment: "negative" },
  { id: "bn027", text: "Brand safety risk, boycott trend start hobe", sentiment: "negative" },
  { id: "bn028", text: "Inclusion message ta authentic lagche", sentiment: "positive" },
  { id: "bn029", text: "Regulatory warning ashte pare ei claim e", sentiment: "negative" },
  { id: "bn030", text: "Youth audience er jonno perfect tone", sentiment: "positive" },
  { id: "bn031", text: "Hoarding er accusation uthte pare", sentiment: "negative" },
  { id: "bn032", text: "Rival brand er meme reply ready", sentiment: "negative" },
  { id: "bn033", text: "Low bandwidth e load hobe na, design heavy", sentiment: "neutral" },
  { id: "bn034", text: "Influencer match ta off-brand", sentiment: "negative" },
  { id: "bn035", text: "Social commerce trust issue abar highlight", sentiment: "negative" },
  { id: "bn036", text: "Campaign ta culturally sensitive", sentiment: "positive" },
  { id: "bn037", text: "Price manipulation vibe from slogan", sentiment: "negative" },
  { id: "bn038", text: "Activist group protest korbe likely", sentiment: "negative" },
  { id: "bn039", text: "Banglish mix ta natural, not forced", sentiment: "positive" },
  { id: "bn040", text: "Apology post lagbe 48 hour er moddhe", sentiment: "negative" },
  { id: "bn041", text: "F-commerce seller der jonno helpful ad", sentiment: "positive" },
  { id: "bn042", text: "Celebrity casting controversial hobe", sentiment: "negative" },
  { id: "bn043", text: "DBID registration mention kora uchit", sentiment: "neutral" },
  { id: "bn044", text: "CCMS complaint link missing, non-compliant", sentiment: "negative" },
  { id: "bn045", text: "Gen-Z er meme culture e fit kore na", sentiment: "negative" },
  { id: "bn046", text: "Rural audience er pain point touch koreche", sentiment: "positive" },
  { id: "bn047", text: "Sarcasm miss kore positive niye nibe", sentiment: "negative" },
  { id: "bn048", text: "Competitor already similar campaign chalay", sentiment: "neutral" },
  { id: "bn049", text: "Backlash manageable if they fix copy", sentiment: "mixed" },
  { id: "bn050", text: "Overall solid campaign, minor tweaks needed", sentiment: "positive" },
] as const;
